// Import all route files
export * from './admin-logs.js';
export * from './admin.js';
export * from './ai-career-coach.js';
export * from './analytics.js';
export * from './auth-advanced.js';
export * from './career-roadmap.js';
export * from './career.js';
export * from './community.js';
export * from './content-management.js';
export * from './courses.js';
export * from './dashboard.js';
export * from './industry-experts.js';
export * from './learning-resources.js';
export * from './mentor-journey.js';
export * from './mentor.js';
export * from './rbac.js';
export * from './search.js';
export * from './upload.js';
