// Import all route files
export * from './admin-logs';
export * from './admin';
export * from './ai-career-coach';
export * from './analytics';
export * from './auth-advanced';
export * from './career-roadmap';
export * from './career';
export * from './community';
export * from './content-management';
export * from './courses';
export * from './dashboard';
export * from './industry-experts';
export * from './learning-resources';
export * from './mentor-journey';
export * from './mentor';
export * from './rbac';
export * from './search';
export * from './upload';
